improve switch_sennheiser_profile
Signed-off-by: Maximilian Huber <gh@maxhbr.de>

diff --git a/nixos/desktop/modules/pulseaudio/bin/switch_sennheiser_profile b/nixos/desktop/modules/pulseaudio/bin/switch_sennheiser_profile
--- a/nixos/desktop/modules/pulseaudio/bin/switch_sennheiser_profile
+++ b/nixos/desktop/modules/pulseaudio/bin/switch_sennheiser_profile
@@ -8,44 +8,60 @@ set -o pipefail
 
 export LC_ALL=C
 
+if [[ "$1" == "-h" ]]; then
+    cat <<EOF
+  \$ $0 [h|m|-h]
+EOF
+    exit 0
+fi
+
 function main {
-  readonly sennheiser_profile="$(pactl list cards \
+    readonly sennheiser_profile="$(pactl list cards \
                                      | awk '/MB 660/' RS="\n\n" ORS="\n\n")"
-  if [[ -z "$sennheiser_profile" ]]; then
-    echo "could not determine \$sennheiser_profile, headset probably not connected"
-    exit 1
-  fi
-  readonly pactl_name="$(printf "$sennheiser_profile" \
+    if [[ -z "$sennheiser_profile" ]]; then
+        echo "could not determine \$sennheiser_profile, headset probably not connected"
+        exit 1
+    fi
+
+    readonly pactl_name="$(printf "$sennheiser_profile" \
                              | grep 'Name: ' \
                              | tail -n1 \
                              | sed -r 's/.*Name://' \
                              | cut -d' ' -f2)"
-  if [[ -z "$pactl_name" ]]; then
-    echo "could not determine \$pactl_name, headset probably not connected"
-    exit 1
-  fi
-  readonly pactl_active_profile="$(printf "$sennheiser_profile" \
+    if [[ -z "$pactl_name" ]]; then
+        echo "could not determine \$pactl_name, headset probably not connected"
+        exit 1
+    fi
+
+    if [[ "$1" == "h" ]]; then
+        readonly pactl_target_profile="headset_head_unit"
+    elif [[ "$1" == "m" ]]; then
+        readonly pactl_target_profile="a2dp_sink"
+    else
+        readonly pactl_active_profile="$(printf "$sennheiser_profile" \
                                        | grep -oP 'Active Profile: ([^ ]+)' \
                                        | sed -r 's/.*: *//')"
-  if [[ -z "$pactl_active_profile" ]]; then
-    echo "could not determine \$pactl_active_profile, headset probably not connected"
-    exit 1
-  fi
-  readonly pactl_other_profile="$(printf "$sennheiser_profile" \
+        if [[ -z "$pactl_active_profile" ]]; then
+            echo "could not determine \$pactl_active_profile, headset probably not connected"
+            exit 1
+        fi
+
+        readonly pactl_other_profile="$(printf "$sennheiser_profile" \
                                       | grep -oP 'profile.s.: .+' \
                                       | sed -r 's/.*: *//;s/, //' \
                                       | sed -r "s/${pactl_active_profile}//")"
-  if [[ -z "$pactl_other_profile" ]]; then
-    echo "could not determine \$pactl_other_profile, headset probably not connected"
-    exit 1
-  fi
+        if [[ -z "$pactl_other_profile" ]]; then
+            echo "could not determine \$pactl_other_profile, headset probably not connected"
+            exit 1
+        fi
 
-  readonly pactl_first_other_profile="$(printf "$pactl_other_profile" \
-                                            | head -1 \
-                                            | cut -f 1 -d " ")"
+        readonly pactl_target_profile="$(printf "$pactl_other_profile" \
+                                       | head -1 \
+                                       | cut -f 1 -d " ")"
+    fi
 
-  pactl set-card-profile "${pactl_name}" "${pactl_first_other_profile}"
-  echo "$pactl_first_other_profile"
+    pactl set-card-profile "${pactl_name}" "${pactl_target_profile}"
+    echo "$pactl_target_profile"
 }
 
 main "$@"
